# docker-compose.yml

services:
  web:
    build: .
    # The command is now in the Dockerfile's CMD, so we remove it from here.
    # The entrypoint is also in the Dockerfile.
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - pnm_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  pnm_data:
