version: '3.9'

services:
  web:
    build: .
    command: gunicorn pythonnetworkmonitor.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env # This will load environment variables from a .env file
    depends_on:
      - db
    # Set entrypoint to run migrations before starting the web server
    # This is a common pattern for Django apps in Docker
    entrypoint:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        exec gunicorn pythonnetworkmonitor.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:16-alpine # Using a recent, lightweight PostgreSQL image
    volumes:
      - pnm_data:/var/lib/postgresql/data/ # Persistent data volume
    env_file:
      - .env # This will load environment variables from a .env file

volumes:
  pnm_data:
