# docker-compose.yml

services:
  web:
    build: .
    # The command is now in the Dockerfile's CMD, so we remove it from here.
    # The entrypoint is also in the Dockerfile.
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    # The command to start a celery worker
    command: celery -A pythonnetworkmonitor worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A pythonnetworkmonitor beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=pythonnetworkmonitor.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    volumes:
      - pnm_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7-alpine

volumes:
  pnm_data:
