# Generated by Django 5.2.4 on 2025-07-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for the host (e.g., 'Router_1', 'Web_Server')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="The IP address of the host.", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the host.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this host is currently being monitored.",
                    ),
                ),
                (
                    "added_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this host was added.",
                    ),
                ),
                (
                    "ping_interval",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PingHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_rtt", models.FloatField(blank=True, null=True)),
                ("max_rtt", models.FloatField(blank=True, null=True)),
                ("avg_rtt", models.FloatField(blank=True, null=True)),
                ("packet_loss", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("was_successful", models.BooleanField(blank=True)),
                ("last_downtime", models.DateTimeField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        help_text="The host this ping result belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ping_results",
                        to="network_monitor.host",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
