# Generated by Django 5.2.4 on 2025-07-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="last_ping_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The last time this host was last ping.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hostdowntimeevent",
            name="reason",
            field=models.CharField(
                blank=True,
                help_text="Optional reason for downtime (e.g., 'network outage', 'server restart').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="ping_interval",
            field=models.IntegerField(
                blank=True,
                default=60,
                help_text="How many seconds between pings.",
                null=True,
            ),
        ),
    ]
