# Generated by Django 5.2.4 on 2025-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinghost",
            name="packet_loss",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
