# Generated by Django 5.2.4 on 2025-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "network_monitor",
            "0002_host_last_ping_time_hostdowntimeevent_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="last_down_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The last time this host was last down.",
                null=True,
            ),
        ),
    ]
