# Generated by Django 5.2.4 on 2025-07-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0002_pinghost_packet_loss"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pinghost",
            old_name="hostname",
            new_name="host",
        ),
    ]
