# Generated by Django 5.2.4 on 2025-07-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0003_host_last_down_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="host",
            old_name="last_ping_time",
            new_name="last_ping_attempt",
        ),
    ]
