# Generated by Django 5.2.4 on 2025-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0003_rename_hostname_pinghost_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinghost",
            name="is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
