# Generated by Django 5.2.4 on 2025-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0004_alter_pinghost_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinghost",
            name="is_active",
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
