# Generated by Django 5.2.4 on 2025-07-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0005_alter_pinghost_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinghost",
            name="last_downtime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
