# Generated by Django 5.2.4 on 2025-07-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "network_monitor",
            "0007_host_alter_pinghost_options_pinghost_ping_interval_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="pinghost",
            old_name="is_active",
            new_name="was_successful",
        ),
    ]
