# Generated by Django 5.2.4 on 2025-07-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0008_rename_is_active_pinghost_was_successful"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pinghost",
            name="ping_interval",
        ),
        migrations.AddField(
            model_name="host",
            name="ping_interval",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
