# Generated by Django 5.2.4 on 2025-07-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0009_remove_pinghost_ping_interval_host_ping_interval"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pinghost",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="pinghost",
            name="host",
            field=models.ForeignKey(
                blank=True,
                help_text="The host this ping result belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ping_results",
                to="network_monitor.host",
            ),
        ),
    ]
